version: '3.8'

services:
  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: projectalgo-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Environment variables are loaded from .env file
    ports:
      - "5000:5000"
    volumes:
      - ./server/codes:/app/codes
      - ./server/inputs:/app/inputs
      - ./server/outputs:/app/outputs
      # For development: Mount the source code for live reload
      - ./server:/app
      - /app/node_modules
    networks:
      - projectalgo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: projectalgo-client
    restart: unless-stopped
    env_file:
      - ./client/.env.production
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    volumes:
      # For development: Mount the source code for live reload
      - ./client:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - server
    networks:
      - projectalgo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  projectalgo-network:
    driver: bridge
